[package]
name = "superr_optimizers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.1.0"
num-format = "0.4.4"
rand = "0.8.5"
rayon = "1.10.0"
superr_vm = { path = "../superr_vm/" }
