[workspace]
resolver = "2"
members = [
    "crates/superr_vm",
    "crates/superr_optimizers",
    "crates/superr",
    "crates/superr_inspect",
    "crates/qua_lexer",
    "crates/qua_ast",
    "crates/qua_parser"
]
