[package]
name = "superr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
superr_vm = { path = "../superr_vm/" }
superr_optimizers = { path = "../superr_optimizers/" }
